# Supabase Configuration for SceneScout v14

project_id = "ldgbjmotttuomxzwujrt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://scenescout.app"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true

[auth.sms]
enable_signup = false
enable_confirmations = false

# OAuth providers (configure as needed)
# [auth.external.apple]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.azure]
# enabled = false
# client_id = ""
# secret = ""
# url = ""

# [auth.external.bitbucket]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.discord]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.facebook]
# enabled = false
# client_id = ""
# secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
skip_nonce_check = false

# [auth.external.keycloak]
# enabled = false
# client_id = ""
# secret = ""
# url = ""

# [auth.external.linkedin]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.notion]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.twitch]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.twitter]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.slack]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.spotify]
# enabled = false
# client_id = ""
# secret = ""

# [auth.external.workos]
# enabled = false
# client_id = ""
# secret = ""
# url = ""

# [auth.external.zoom]
# enabled = false
# client_id = ""
# secret = ""

[edge_runtime]
enabled = true
inspector_port = 54330

# Edge Functions configuration
[functions.ingest_ticketmaster]
verify_jwt = false

[functions.ingest_eventbrite]
verify_jwt = false

[functions.ingest_songkick]
verify_jwt = false

[functions.ingest_meetup]
verify_jwt = false

[functions.ingest_places_google]
verify_jwt = false

[functions.ingest_places_yelp]
verify_jwt = false

[functions.daily_digest]
verify_jwt = false

[functions.reminders]
verify_jwt = false

[functions.enrich_images]
verify_jwt = false

[functions.hotness_ml]
verify_jwt = false

# New scheduled scraping functions
[functions.scheduled-scraper]
verify_jwt = false

[functions.city-scraper]
verify_jwt = false

[functions.venue-scraper]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.rpc-functions]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Setup BigQuery project to use analytics

[realtime]
enabled = true
ip_version = "IPv4"

# Environment variables (set these in production)
# TICKETMASTER_API_KEY=your_key_here
# EVENTBRITE_TOKEN=your_token_here
# SONGKICK_API_KEY=your_key_here
# MEETUP_ACCESS_TOKEN=your_token_here
# GOOGLE_PLACES_API_KEY=your_key_here
# YELP_API_KEY=your_key_here
# OPENAI_API_KEY=your_key_here
# RESEND_API_KEY=your_key_here
# CLOUDINARY_CLOUD_NAME=your_cloudinary_name
# GITHUB_CLIENT_ID=your_github_client_id
# GITHUB_CLIENT_SECRET=your_github_client_secret
# GOOGLE_CLIENT_ID=your_google_client_id
# GOOGLE_CLIENT_SECRET=your_google_client_secret

# Webhook secrets for scheduled scraping
# EVENTBRITE_WEBHOOK_SECRET=your_eventbrite_webhook_secret
# TICKETMASTER_WEBHOOK_SECRET=your_ticketmaster_webhook_secret
# INTERNAL_WEBHOOK_SECRET=your_internal_webhook_secret