/**
 * Shared TypeScript types for SceneScout Supabase Edge Functions
 * This file contains the database schema types used across all functions
 */

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          location_lat: number | null;
          location_lng: number | null;
          location_name: string | null;
          timezone: string | null;
          push_token: string | null;
          notification_preferences: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          location_name?: string | null;
          timezone?: string | null;
          push_token?: string | null;
          notification_preferences?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          location_lat?: number | null;
          location_lng?: number | null;
          location_name?: string | null;
          timezone?: string | null;
          push_token?: string | null;
          notification_preferences?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          start_time: string;
          end_time: string | null;
          timezone: string;
          venue_id: string | null;
          organizer_id: string | null;
          category: string;
          subcategory: string | null;
          tags: string[];
          price_min: number | null;
          price_max: number | null;
          price_currency: string;
          ticket_url: string | null;
          image_url: string | null;
          image_alt_text: string | null;
          image_analysis: any | null;
          image_enhanced_url: string | null;
          image_thumbnail_url: string | null;
          image_processed: boolean | null;
          source: string;
          external_id: string;
          status: string;
          age_restriction: string | null;
          capacity: number | null;
          attendee_count: number | null;
          hotness_score: number;
          hotness_confidence: number | null;
          hotness_factors: any | null;
          hotness_explanation: string | null;
          created_at: string;
          updated_at: string;
          last_updated: string;
        };
        Insert: {
          id: string;
          title: string;
          description?: string | null;
          start_time: string;
          end_time?: string | null;
          timezone: string;
          venue_id?: string | null;
          organizer_id?: string | null;
          category: string;
          subcategory?: string | null;
          tags?: string[];
          price_min?: number | null;
          price_max?: number | null;
          price_currency?: string;
          ticket_url?: string | null;
          image_url?: string | null;
          image_alt_text?: string | null;
          image_analysis?: any | null;
          image_enhanced_url?: string | null;
          image_thumbnail_url?: string | null;
          image_processed?: boolean | null;
          source: string;
          external_id: string;
          status?: string;
          age_restriction?: string | null;
          capacity?: number | null;
          attendee_count?: number | null;
          hotness_score?: number;
          hotness_confidence?: number | null;
          hotness_factors?: any | null;
          hotness_explanation?: string | null;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          start_time?: string;
          end_time?: string | null;
          timezone?: string;
          venue_id?: string | null;
          organizer_id?: string | null;
          category?: string;
          subcategory?: string | null;
          tags?: string[];
          price_min?: number | null;
          price_max?: number | null;
          price_currency?: string;
          ticket_url?: string | null;
          image_url?: string | null;
          image_alt_text?: string | null;
          image_analysis?: any | null;
          image_enhanced_url?: string | null;
          image_thumbnail_url?: string | null;
          image_processed?: boolean | null;
          source?: string;
          external_id?: string;
          status?: string;
          age_restriction?: string | null;
          capacity?: number | null;
          attendee_count?: number | null;
          hotness_score?: number;
          hotness_confidence?: number | null;
          hotness_factors?: any | null;
          hotness_explanation?: string | null;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
      };
      venues: {
        Row: {
          id: string;
          name: string;
          address: string;
          city: string;
          state: string;
          postal_code: string;
          country: string;
          latitude: number;
          longitude: number;
          phone: string | null;
          website: string | null;
          timezone: string;
          capacity: number | null;
          venue_type: string;
          category: string | null;
          subcategory: string | null;
          rating: number | null;
          review_count: number;
          price_level: number | null;
          amenities: string[];
          accessibility_features: string[];
          parking_info: string | null;
          description: string | null;
          opening_hours: string[];
          photos: any[] | null;
          images_processed: boolean | null;
          source: string;
          external_id: string;
          created_at: string;
          updated_at: string;
          last_updated: string;
        };
        Insert: {
          id: string;
          name: string;
          address: string;
          city: string;
          state: string;
          postal_code: string;
          country: string;
          latitude: number;
          longitude: number;
          phone?: string | null;
          website?: string | null;
          timezone: string;
          capacity?: number | null;
          venue_type: string;
          category?: string | null;
          subcategory?: string | null;
          rating?: number | null;
          review_count?: number;
          price_level?: number | null;
          amenities?: string[];
          accessibility_features?: string[];
          parking_info?: string | null;
          description?: string | null;
          opening_hours?: string[];
          photos?: any[] | null;
          images_processed?: boolean | null;
          source: string;
          external_id: string;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string;
          city?: string;
          state?: string;
          postal_code?: string;
          country?: string;
          latitude?: number;
          longitude?: number;
          phone?: string | null;
          website?: string | null;
          timezone?: string;
          capacity?: number | null;
          venue_type?: string;
          category?: string | null;
          subcategory?: string | null;
          rating?: number | null;
          review_count?: number;
          price_level?: number | null;
          amenities?: string[];
          accessibility_features?: string[];
          parking_info?: string | null;
          description?: string | null;
          opening_hours?: string[];
          photos?: any[] | null;
          images_processed?: boolean | null;
          source?: string;
          external_id?: string;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
      };
      organizers: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          website: string | null;
          social_media: any | null;
          logo_url: string | null;
          category: string | null;
          member_count: number | null;
          location: string | null;
          timezone: string | null;
          source: string;
          external_id: string;
          created_at: string;
          updated_at: string;
          last_updated: string;
        };
        Insert: {
          id: string;
          name: string;
          description?: string | null;
          website?: string | null;
          social_media?: any | null;
          logo_url?: string | null;
          category?: string | null;
          member_count?: number | null;
          location?: string | null;
          timezone?: string | null;
          source: string;
          external_id: string;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          website?: string | null;
          social_media?: any | null;
          logo_url?: string | null;
          category?: string | null;
          member_count?: number | null;
          location?: string | null;
          timezone?: string | null;
          source?: string;
          external_id?: string;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
      };
      artists: {
        Row: {
          id: string;
          name: string;
          genre: string[];
          description: string | null;
          image_url: string | null;
          external_links: any | null;
          source: string;
          external_id: string;
          created_at: string;
          updated_at: string;
          last_updated: string;
        };
        Insert: {
          id: string;
          name: string;
          genre?: string[];
          description?: string | null;
          image_url?: string | null;
          external_links?: any | null;
          source: string;
          external_id: string;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
        Update: {
          id?: string;
          name?: string;
          genre?: string[];
          description?: string | null;
          image_url?: string | null;
          external_links?: any | null;
          source?: string;
          external_id?: string;
          created_at?: string;
          updated_at?: string;
          last_updated?: string;
        };
      };
      event_artists: {
        Row: {
          event_id: string;
          artist_id: string;
          billing_order: number;
          role: string;
          created_at: string;
        };
        Insert: {
          event_id: string;
          artist_id: string;
          billing_order?: number;
          role?: string;
          created_at?: string;
        };
        Update: {
          event_id?: string;
          artist_id?: string;
          billing_order?: number;
          role?: string;
          created_at?: string;
        };
      };
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          categories: string[];
          max_distance: number;
          price_range: any | null;
          notification_frequency: string;
          preferred_times: string[];
          blacklisted_venues: string[];
          favorite_venues: string[];
          tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          categories?: string[];
          max_distance?: number;
          price_range?: any | null;
          notification_frequency?: string;
          preferred_times?: string[];
          blacklisted_venues?: string[];
          favorite_venues?: string[];
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          categories?: string[];
          max_distance?: number;
          price_range?: any | null;
          notification_frequency?: string;
          preferred_times?: string[];
          blacklisted_venues?: string[];
          favorite_venues?: string[];
          tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      user_reminders: {
        Row: {
          id: string;
          user_id: string;
          event_id: string;
          reminder_time: string;
          notification_method: string;
          status: string;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_id: string;
          reminder_time: string;
          notification_method: string;
          status?: string;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_id?: string;
          reminder_time?: string;
          notification_method?: string;
          status?: string;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          data: any | null;
          read: boolean;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          data?: any | null;
          read?: boolean;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          data?: any | null;
          read?: boolean;
          sent_at?: string | null;
          created_at?: string;
        };
      };
      event_images: {
        Row: {
          id: string;
          event_id: string;
          original_url: string;
          enhanced_url: string | null;
          thumbnail_url: string | null;
          alt_text: string | null;
          analysis_data: any | null;
          enhancement_applied: boolean;
          processed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          original_url: string;
          enhanced_url?: string | null;
          thumbnail_url?: string | null;
          alt_text?: string | null;
          analysis_data?: any | null;
          enhancement_applied?: boolean;
          processed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          original_url?: string;
          enhanced_url?: string | null;
          thumbnail_url?: string | null;
          alt_text?: string | null;
          analysis_data?: any | null;
          enhancement_applied?: boolean;
          processed_at?: string;
          created_at?: string;
        };
      };
      venue_images: {
        Row: {
          id: string;
          venue_id: string;
          original_url: string;
          enhanced_url: string | null;
          thumbnail_url: string | null;
          alt_text: string | null;
          analysis_data: any | null;
          enhancement_applied: boolean;
          processed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          venue_id: string;
          original_url: string;
          enhanced_url?: string | null;
          thumbnail_url?: string | null;
          alt_text?: string | null;
          analysis_data?: any | null;
          enhancement_applied?: boolean;
          processed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          venue_id?: string;
          original_url?: string;
          enhanced_url?: string | null;
          thumbnail_url?: string | null;
          alt_text?: string | null;
          analysis_data?: any | null;
          enhancement_applied?: boolean;
          processed_at?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}