name: Database Operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Database operation'
        required: true
        default: 'push'
        type: choice
        options:
        - push
        - reset
        - seed
        - migrate

jobs:
  database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Supabase CLI
        run: npm install -g supabase
        
      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
      - name: Run database operation
        run: |
          case "${{ github.event.inputs.operation }}" in
            "push")
              supabase db push
              ;;
            "reset")
              supabase db reset --linked
              ;;
            "seed")
              supabase seed
              ;;
            "migrate")
              supabase migration up
              ;;
          esac
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
